set shell := ["bash", "-euo", "pipefail", "-c"]

default: check

fix:
    golangci-lint fmt
    golangci-lint run --fix ./...

check:
    golangci-lint fmt --diff
    golangci-lint run ./...

build:
    go build ./...

e2e:
    go test -race -v -parallel=2 ./...
