set shell := ["bash", "-euo", "pipefail", "-c"]

default:
    @just --list

fix:
    golangci-lint fmt
    golangci-lint run --fix ./...

check:
    golangci-lint fmt --diff
    golangci-lint run ./...

build:
    go build ./...

e2e:
	docker build --tag e2e-example:local .
	go test -race -v -shuffle=on -count=1 -parallel=2 ./...
